AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  Bucket:
    Type: String
  Key:
    Type: String
    Default: shields
Resources:
  SetShield:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: handler
      CodeUri: ../bin
      MemorySize: 128
      Timeout: 30
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref Bucket
      Events:
        BuildStatus:
          Type: 'EventBridgeRule'
          Properties:
            Pattern:
              source:
                - 'aws.codebuild'
              detail-type:
                - 'CodeBuild Build State Change'
              detail:
                build-status:
                  - IN_PROGRESS
                  - SUCCEEDED
                  - FAILED
                  - STOPPED
                  - TIMED_OUT
                  - FAULT
      Environment:
        Variables:
          BUCKET: !Ref Bucket
          KEY: !Ref Key
          AWS_SDK_LOAD_CONFIG: true
