AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  Bucket:
    Type: String
  Key:
    Type: String
    Default: shields
Resources:
  SyncRecords:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: go1.x
      Handler: cloudWatchBuildEvent
      CodeUri: ../bin
      MemorySize: 128
      Timeout: 30
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref Bucket
      Events:
        BuildStatus:
          Type: 'EventBridgeRule'
          Properties:
            Pattern:
              detail-type:
                - 'CodeBuild Build State Change'
                
      Environment:
        Variables:
          BUCKET: !Sub ${Bucket}/${Key}
